set(PROSILICA_INCLUDE_DIRS)
set(PROSILICA_LIBRARIES)
set(PROSILICA_DEFINITIONS)

find_path(PROSILICA_INCLUDE_DIRS "PvApi.h")
find_library(PROSILICA_LIBRARIES PvAPI)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Prosilica DEFAULT_MSG
  PROSILICA_LIBRARIES
  PROSILICA_INCLUDE_DIRS
)
